# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

# default_platform(:ios)

platform :ios do
  desc "deploy ios to test flight"
  lane :beta do
    upload_to_testflight(
        ipa: "platforms/ios/build/device/Plastic Patrol.ipa",
        distribute_external: false,
        skip_waiting_for_build_processing: false,
        changelog: ENV["TRAVIS_COMMIT_MESSAGE"]
    )
    end
end

platform :android do
  desc "deploy android to beta"
  lane :beta do
    upload_to_play_store(
      apk: "./platforms/android/app/build/outputs/apk/release/app-release.apk",
      track: "beta",
      skip_upload_metadata: true,
      skip_upload_aab: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      json_key: "GooglePlayAndroidDeveloper.json"
    )
    end
end
